package com.example.note_task_app.ui.theme

val bluePrimary = 0xFF1E88E5.toInt()
val blueOnPrimary = 0xFFFFFFFF.toInt()
val bluePrimaryContainer = 0xFFD6E3FF.toInt()
val blueOnPrimaryContainer = 0xFF001F3F.toInt()
val blueSecondary = 0xFF64B5F6.toInt()
val blueOnSecondary = 0xFF000000.toInt()
val blueTertiary = 0xFF7D5260.toInt()
val blueOnTertiary = 0xFFFFFFFF.toInt()

val redPrimary = 0xFFE53935.toInt()
val redOnPrimary = 0xFFFFFFFF.toInt()
val redPrimaryContainer = 0xFFFFD6D6.toInt()
val redOnPrimaryContainer = 0xFF4A0000.toInt()
val redSecondary = 0xFFEF5350.toInt()
val redOnSecondary = 0xFF000000.toInt()
val redTertiary = 0xFF7D5260.toInt()
val redOnTertiary = 0xFFFFFFFF.toInt()

val greenPrimary = 0xFF43A047.toInt()
val greenOnPrimary = 0xFFFFFFFF.toInt()
val greenPrimaryContainer = 0xFFC8E6C9.toInt()
val greenOnPrimaryContainer = 0xFF003300.toInt()
val greenSecondary = 0xFF66BB6A.toInt()
val greenOnSecondary = 0xFF000000.toInt()
val greenTertiary = 0xFF7D5260.toInt()
val greenOnTertiary = 0xFFFFFFFF.toInt()

val orangePrimary = 0xFFFB8C00.toInt()
val orangeOnPrimary = 0xFFFFFFFF.toInt()
val orangePrimaryContainer = 0xFFFFE0B2.toInt()
val orangeOnPrimaryContainer = 0xFF3E1A00.toInt()
val orangeSecondary = 0xFFFFA726.toInt()
val orangeOnSecondary = 0xFF000000.toInt()
val orangeTertiary = 0xFF7D5260.toInt()
val orangeOnTertiary = 0xFFFFFFFF.toInt()

val violetPrimary = 0xFF8E24AA.toInt()
val violetOnPrimary = 0xFFFFFFFF.toInt()
val violetPrimaryContainer = 0xFFF3E5F5.toInt()
val violetOnPrimaryContainer = 0xFF2A0033.toInt()
val violetSecondary = 0xFFCE93D8.toInt()
val violetOnSecondary = 0xFF000000.toInt()
val violetTertiary = 0xFF7D5260.toInt()
val violetOnTertiary = 0xFFFFFFFF.toInt()